version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: social-media-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - ENVIRONMENT=development
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    networks:
      - social-media-network

  # React Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: social-media-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - social-media-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: social-media-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social-media-network

  # ClamAV for malware scanning
  clamav:
    image: clamav/clamav:stable
    container_name: social-media-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    networks:
      - social-media-network

volumes:
  redis_data:
  clamav_data:

networks:
  social-media-network:
    driver: bridge 